"""rename address

Revision ID: b7cd885a8cf2
Revises: f6269bfe4e3d
Create Date: 2024-07-05 16:40:59.684072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7cd885a8cf2'
down_revision = 'f626d9bfe4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='address')
    # ### end Alembic commands ###
